version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run:
        command: echo "This is working"